# Setup
title:               Allan Nguyen
tagline:             'Computer Scientist, Teaching Assistant, Researcher, Developer'
description:         ''
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Allan Nguyen
  url:               allannnguyen.github.io
  email:             allan.n.nguyen@gmail.com

# Custom vars
version:             1.0.0
